import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Reservations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="reservations.css"></link>
      </Head>
      <div className="isolate bg-white">
        <main>

        <div style={{backgroundColor: "white", overflow: "hidden", marginLeft: "32px", textAlign: "center"}}>
            <a href="reservations" style = {{float: "left", color: "black", textAlign: "center", padding: "14px 16px", fontSize: "40px", textDecoration: "none", fontFamily: "papyrus", borderWidth: "2px", borderColor: "black"}}>Reservations</a>&nbsp;&nbsp;&nbsp;
            <a href="menu" style = {{float: "left", color: "black", textAlign: "center", padding: "14px 16px", fontSize: "40px", textDecoration: "none", fontFamily: "papyrus", borderRightWidth: "2px", borderTopWidth: "2px", borderBottomWidth: "2px", borderColor: "black"}}>Menu</a>&nbsp;&nbsp;&nbsp;
            <a href="cart" style = {{backgroundColor: "orange", color: "white", float: "left", textAlign: "center", padding: "14px 16px", fontSize: "40px", textDecoration: "none", fontFamily: "papyrus", borderRightWidth: "2px", borderTopWidth: "2px", borderBottomWidth: "2px", borderColor: "black"}}>Cart</a>          
            
        </div>
        
          <div className="relative px-6 lg:px-8">
                <div style={{ backgroundColor: "#CC0000", paddingLeft: 16, margin: 0, fontFamily: "Arial, Helvetica, sans-serif"}}>
                <br></br>
                <table style={{backgroundColor: "white"}}>
                            <tr>
                                <th>Order    </th>
                                <th>  </th>
                                <th>  </th>
                            </tr>
                            <tr>
                                <td>  </td>
                                <td>  </td>
                                <td><form><input type="submit" value=" Remove " name = "remove" style={{backgroundColor: "orange"}}></input></form></td>
                            </tr>
                </table>
                <br></br>

                <div style={{backgroundColor: "white", marginRight: "550px"}}>
                    
                    <p style = {{fontSize: "25px", fontFamily: "papyrus"}}>Total:</p>
                    <br></br>
                    <form>
                    $   <input type="text" id="date" name="date" placeholder = "Card Number" style={{borderColor: "black", borderBottomWidth: "2px", textAlign: "center"}}></input>
                    &nbsp;
                        <input type="text" id="date" name="date" placeholder = "Card Expiration Date" style={{borderColor: "black", borderBottomWidth: "2px", textAlign: "center"}}></input>
                        &nbsp;
                        <input type="text" id="date" name="date" placeholder = "Security Code"style={{borderColor: "black", borderBottomWidth: "2px", textAlign: "center"}}></input>
                        &nbsp;
                        <input type="text" id="date" name="date" placeholder = "Card Holder Name" style={{borderColor: "black", borderBottomWidth: "2px", textAlign: "center"}}></input>
                        &nbsp;
                        <input type="text" id="date" name="date" placeholder = "Name for the Order" style={{borderColor: "black", borderBottomWidth: "2px", textAlign: "center"}}></input>
                        &nbsp; &nbsp;
                       <input type="submit" value = " Submit " style = {{backgroundColor: "orange", borderColor: "black", borderTopWidth: "2px", borderLeftWidth: "2px", borderRightWidth: "3px", borderBottomWidth: "4px"}}></input></form>
                    <br></br>
                </div>
                <br></br>
                </div>
          </div>
          <footer style = {{backgroundColor: "gray", textAlign: "right", marginLeft: "32px", marginRight: "32px"}}>
          <a href="login" style={{fontSize: "12px"}}><u><b>Employee / Restaurant View</b></u>&nbsp;&nbsp;</a>
          </footer>
        </main>
      </div>
    </>
  );
}