import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Reservations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="reservations.css"></link>
      </Head>
      <div className="isolate bg-white">
        <main>

        <div className="topnav">
            <a href="reservations">Reservations</a>
            <a href="menu">Menu</a>
            <a className = "active" href="cart">Cart</a>
        </div>
        
          <div className="relative px-6 lg:px-8">
                <div style={{ backgroundColor: "#CC0000", paddingLeft: 16, margin: 0, fontFamily: "Arial, Helvetica, sans-serif"}}>
                <br></br>
                <table style={{backgroundColor: "white"}}>
                            <tr>
                                <th>Order    </th>
                                <th>  </th>
                                <th>  </th>
                            </tr>
                            <tr>
                                <td>  </td>
                                <td>  </td>
                                <td><form><input type="submit" value=" Remove " name = "remove" style={{backgroundColor: "orange"}}></input></form></td>
                            </tr>
                </table>
                <br></br>

                <div style={{backgroundColor: "white"}}>
                    Total:
                    <br></br>
                    <form>
                    $   <input type="text" id="date" name="date" placeholder = "Card Number" style={{borderColor: "green", borderWidth: "2px"}}></input>
                    &nbsp;
                        <input type="text" id="date" name="date" placeholder = "Card Expiration Date" style={{borderColor: "green", borderWidth: "2px"}}></input>
                        &nbsp;
                        <input type="text" id="date" name="date" placeholder = "Security Code"style={{borderColor: "green", borderWidth: "2px"}}></input>
                        &nbsp;
                        <input type="text" id="date" name="date" placeholder = "Card Holder Name" style={{borderColor: "green", borderWidth: "2px"}}></input>
                        &nbsp;
                        <input type="text" id="date" name="date" placeholder = "Name for the Order" style={{borderColor: "green", borderWidth: "2px"}}></input>
                        &nbsp; &nbsp;
                       <input type="submit" value = " Submit " style = {{backgroundColor: "orange"}}></input></form>
                    <br></br>
                </div>
                <br></br>
                </div>
          </div>
        </main>
      </div>
    </>
  );
}