import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Reservations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="reservations.css"></link>
        <script src = "login.js"></script>
      </Head>
      <div className="isolate bg-white">
        <main>

          <div className="relative px-6 lg:px-8">
          <div style={{ backgroundColor: "#CC0000", margin: 0, fontFamily: "Comic Sans, Arial, Helvetica, sans-serif"}}>
            <br></br>
            <div style={{backgroundColor: "white", marginLeft: "500px", marginRight: "500px", textAlign: "center", fontFamily: "Comic Sans", fontSize: "20px"}}>
                Log In - Employee View <br></br><br></br>
                <form className = "box" action = "login.tsx" method = "POST">
                <input type="text" id="username" name="username" placeholder = "Restaurant Username" style={{borderColor: "black", borderWidth: "2px", textAlign: "center"}}></input>
                <br></br><br></br>
                <input type="password" id="password" name="password" placeholder = "Restaurant Password" style={{borderColor: "black", borderWidth: "2px", textAlign: "center"}}></input>
                <br></br><br></br>
                <input id = "login" type="submit" value = " Log In " name = "employeelogin" style = {{textAlign: "center", borderColor: "black", borderRightWidth: "3px", borderLeftWidth: "2px", borderTopWidth: "2px", borderBottomWidth: "3px"}}></input>
                <br></br><br></br>
                <a href = "reservationsmade" style = {{borderColor: "black", borderWidth: "2px"}}> Quick Link Until Login Form is Set Up</a>
                </form>
            </div>
        <br></br>
          </div>
              
          </div>
          <footer style = {{backgroundColor: "gray", textAlign: "right", marginLeft: "32px", marginRight: "32px"}}>
          <a href="main" style={{fontSize: "12px"}}><u><b>Customer View</b></u>&nbsp;&nbsp;</a>
          </footer>
        </main>
      </div>
    </>
  );
}