import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Reservations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="reservations.css"></link>
      </Head>
      <div className="isolate bg-white">
        <main>

        <div className="topnav">
            <a href="reservations">Reservations</a>
            <a className = "active" href="menu">Menu</a>
            <a href="#cart">Cart</a>
        </div>
          <div className="relative px-6 lg:px-8">
                <div style={{ backgroundColor: "#CC0000", paddingLeft: 16, margin: 0, fontFamily: "Arial, Helvetica, sans-serif"}}>
                        <table style={{backgroundColor: "white"}}>
                            <tr>
                                <th>Item   </th>
                                <th>Price</th>
                                <th><button></button></th>
                            </tr>
                            <tr>
                                <td>Cheeseburger   </td>
                                <td>$10</td>
                                <td><button>   </button></td>
                            </tr>
                            <tr>
                                <td>Pizza   </td>
                                <td>$12</td>
                                <td><button>   </button></td>
                            </tr>
                            <tr>
                                <td>Chicken Salad   </td>
                                <td>$9</td>
                                <td><button>   </button></td>
                            </tr>
                            <tr>
                                <td>Shrimp Tacos   </td>
                                <td>$13</td>
                                <td><button>   </button></td>
                            </tr>
                            <tr>
                                <td>Soup of the Day   </td>
                                <td>$5</td>
                                <td><button>   </button></td>
                            </tr>
                            <tr>
                                <td>Pasta   </td>
                                <td>$8</td>
                                <td><button>   </button></td>
                            </tr>                            
                        </table>
                </div>
          </div>
        </main>
      </div>
    </>
  );
}