import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Reservations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="reservations.css"></link>
      </Head>
      <div className="isolate bg-white">
        <main>

        <div className="topnav">
            <a href="reservations">Reservations</a>
            <a className = "active" href="menu">Menu</a>
            <a href="#cart">Cart</a>
        </div>
        
          <div className="relative px-6 lg:px-8">
                <div style={{ backgroundColor: "#CC0000", paddingLeft: 16, margin: 0, fontFamily: "Arial, Helvetica, sans-serif"}}>
                  <br></br>
                        <table style={{backgroundColor: "white"}}>
                            <tr>
                                <th>Item     </th>
                                <th> &nbsp; &nbsp; Price &nbsp;    </th>
                                <th>  Submit  </th>
                            </tr>
                            <tr>
                                <td>Cheeseburger   </td>
                                <td>&nbsp;&nbsp;&nbsp;$10</td>
                                <td><form><input type="submit" value=" Submit " name = "cheeseburger" style={{backgroundColor: "white"}}></input></form></td>
                            </tr>
                            <tr>
                                <td>Pizza   </td>
                                <td>&nbsp;&nbsp;&nbsp;$12</td>
                                <td><form><input type="submit" value=" Submit " name = "pizza" style={{backgroundColor: "white"}}></input></form></td>
                            </tr>
                            <tr>
                                <td>Chicken Salad   </td>
                                <td>&nbsp;&nbsp;&nbsp;$9</td>
                                <td><form><input type="submit" value=" Submit " name = "chickensalad" style={{backgroundColor: "white"}}></input></form></td>
                            </tr>
                            <tr>
                                <td>Shrimp Tacos   </td>
                                <td>&nbsp;&nbsp;&nbsp;$13</td>
                                <td><form><input type="submit" value=" Submit " name = "shrimptacos" style={{backgroundColor: "white"}}></input></form></td>
                            </tr>
                            <tr>
                                <td>Soup of the Day   </td>
                                <td>&nbsp;&nbsp;&nbsp;$5</td>
                                <td><form><input type="submit" value=" Submit " name = "soupoftheday" style={{backgroundColor: "white"}}></input></form></td>
                            </tr>
                            <tr>
                                <td>Pasta   </td>
                                <td>&nbsp;&nbsp;&nbsp;$8</td>
                                <td><form><input type="submit" value=" Submit " name = "pasta" style={{backgroundColor: "white"}}></input></form></td>
                            </tr>                            
                        </table>
                        <br></br>
                </div>
          </div>
        </main>
      </div>
    </>
  );
}