import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Reservations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="reservations.css"></link>
      </Head>
      <div className="isolate bg-white">
        <main>

        <div className="topnav">
            <a className="active" href="reservationsmade">Reservations Made</a>
            <a href="updatemenu">Update Menu Items</a>
            <a href="ordersplaced">Orders Placed</a>
        </div>
          <div className="relative px-6 lg:px-8">
                <div style={{ backgroundColor: "#CC0000", paddingLeft: 16, margin: 0, fontFamily: "Arial, Helvetica, sans-serif"}}>
                <br></br>
                <br></br>

                <div style = {{backgroundColor: "white", borderWidth: "3px", borderColor: "black", marginLeft: "100px", marginRight: "100px"}}>
                <br></br>
                <br></br>
                </div>

                <br></br>
                <br></br>

                </div>
          </div>
          <footer style = {{backgroundColor: "gray", textAlign: "right", marginLeft: "32px", marginRight: "32px"}}>
          <a href="main" style={{fontSize: "12px"}}><u><b>Customer View</b></u>&nbsp;&nbsp;</a>
          </footer>
        </main>
      </div>
    </>
  );
}